$sc_gateway_username = 'pnptest';
$sc_gateway_card_allowed = 'visa,mastercard';
$sc_gateway_paymethod = 'credit';
$sc_gateway_avs_level = '';
$sc_gateway_comments = 'no';
$sc_gateway_easycart = 'yes';
$sc_gateway_shipinfo = 'no';
$sc_gateway_send_weight = 'no';
$sc_plugnpay_submit = 'agora.cgi?secpicserve=submit_order.gif';
$sc_plugnpay_change = 'agora.cgi?secpicserve=make_changes.gif';
$sc_plugnpay_verify_message = qq'Please verify the information below.  When you are confident it is correct, click on the \'Submit Order For Processing\' button to go to the PlugnPay site where you will enter your payment information.';
$sc_display_checkout_tos = 'no';
$sc_tos_display_address = qq'AgoraCart<br>
123 Main<br>
Salt Lick City, UT 88888<br>
123-456-7890';
;
$sc_gateway_email = 'webmaster@yourname.com';
$sc_gateway_cc_mail = '';
$sc_gateway_subject = '';
$sc_plugnpay_order_desc = 'PlugnPay AgoraCart Order';
$sc_gateway_message = '';
$sc_gateway_subject_email = '';
$sc_gateway_dontsendmail = 'yes';
$sc_gateway_calculate_tax = 'no';
$sc_gateway_taxrate = '';
$sc_gateway_taxstate = '';
$sc_gateway_success_link = '';
$sc_gateway_badcard_link = '';
$sc_gateway_problem_link = '';
$sc_gateway_use_shipping_calculator = 'no';
$sc_gateway_shipmethod = '';
$sc_gateway_merchant_zip = '';
$sc_gateway_usps_container = '';
$sc_gateway_usps_size = '';
$sc_gateway_ups_rate_chart = '';
$sc_gateway_mailtype = '';
$sc_gateway_machinable = '';
$sc_gateway_rate_chart = '';
$sc_gateway_method_allow = '';
$sc_gateway_userfield1_name = '';
$sc_gateway_userfield1_value = '';
$sc_gateway_userfield2_name = '';
$sc_gateway_userfield2_value = '';
$sc_gateway_userfield3_name = '';
$sc_gateway_userfield3_value = '';
$sc_gateway_userfield4_name = '';
$sc_gateway_userfield4_value = '';
$sc_gateway_userfield5_name = '';
$sc_gateway_userfield5_value = '';
$sc_gateway_userfield6_name = '';
$sc_gateway_userfield6_value = '';
$sc_gateway_userfield7_name = '';
$sc_gateway_userfield7_value = '';
$sc_gateway_userfield8_name = '';
$sc_gateway_userfield8_value = '';
$sc_gateway_userfield9_name = '';
$sc_gateway_userfield9_value = '';
$sc_gateway_userfield10_name = '';
$sc_gateway_userfield10_value = '';
$sc_gateway_userfield11_name = '';
$sc_gateway_userfield11_value = '';
$sc_gateway_userfield12_name = '';
$sc_gateway_userfield12_value = '';
$merchant_live_mode = "no";
1;
