		</TD>
	</TR>
</TABLE>
		</TD>
	</TR>
</TABLE>

<TABLE WIDTH="100%" BORDER="1" CELLSPACING="0" CELLPADDING="0">
	<TR>
		<TD ALIGN="LEFT" bgcolor="#cccccc">
			<B>Note:</B>  We have thousands of <B>New and Used Surplus Machine Tools</B> in stock and ready to ship. Besides Kwik-Switch 200, 300 & 400 tooling systems and tools, we have CAT, BT, CT, Straight Shank, Morse Taper, Acme threaded shank, etc.<BR>Bilz tap adapters, shell mill adapters, stub arbors, MT & JT adapters, boring heads, drill chucks, and much more.
<BR>
			<IMG SRC="http://www.tools-n-gizmos.com/spacer370.gif" ALT="370 pixel space">
				Steve (aka Griz)
  		</TD>
	</TR>
</TABLE>

<TABLE WIDTH="100%" BORDER="1" CELLSPACING="0" CELLPADDING="2">
	<TR BGCOLOR="#CCCCCC">
		<TD ALIGN="CENTER" VALIGN="MIDDLE">
			<B><FONT FACE="Arial" SIZE="-1">
			<A HREF="agora.cgi?cart_id=%%cart_id%%">Home</A>
				<IMG SRC="http://www.tools-n-gizmos.com/VertLine12x29.gif" ALT="Vertical Line"> 
			<A HREF="http://www.tools-n-gizmos.com/store/agora.cgi">Inventory Index</A>
				<IMG SRC="http://www.tools-n-gizmos.com/VertLine12x29.gif" ALT="Vertical Line"> 
			<A HREF="http://www.tools-n-gizmos.com/specs.html">Specifications</A>
				<IMG SRC="http://www.tools-n-gizmos.com/VertLine12x29.gif" ALT="Vertical Line">
			<A HREF="http://www.tools-n-gizmos.com/contact.html">Contact Us</A>
				<IMG SRC="http://www.tools-n-gizmos.com/VertLine12x29.gif" ALT="Vertical Line"> 
			<A HREF="http://www.tools-n-gizmos.com/about.html">About Us</A>
				<IMG SRC="http://www.tools-n-gizmos.com/VertLine12x29.gif" ALT="Vertical Line"> 
			<A HREF="http://www.tools-n-gizmos.com/policy.html">Policies</A>
			</FONT></B>
		</TD>
	</TR>
	<TR>
		<TD ALIGN="CENTER" VALIGN="MIDDLE">
			<B><FONT FACE="Arial" SIZE="-2">Copyright &copy; 2001-2007 Tools-n-Gizmos</FONT></B>
		</TD>
	</TR>		
</TABLE>


