<tr><td class="ac_product_desc" width=170>
<form method="post" action="%%scriptURL%%">
%%make_hidden_fields%%<br/>
%%optionFile%%<br/><p>
<!--BEGIN SELECT QUANTITY BUTTON-->
<table class="ac_add-quantity"><tr><td class="ac_add-quantity">%%QtyBox%%</td>
<td class="ac_add-quantity"><input type="image" name="add_to_cart_button" value="Add To Cart" src="%%ButtonSetURL%%/add_to_cart.gif">
</p></td></tr></table>
<!--END SELECT QUANTITY BUTTON-->
</td><td class="ac_product_image">%%image%%</td>
<td class="ac_product_desc">
<b>%%name%%</b><br/>
%%description%%<br><br/>
<span class="ac_product_price">%%price%%</span><br>
</td></form></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td class="ac_product_desc">
<a href="%%scripturl%%?dc=1&%%href_fields%%" rel="nofollow">Check Out</a></td></tr>
<tr><td colspan=3><hr/></td></tr>